FROM python:3.8-slim-buster
# Install dependencies:
COPY ./requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 5000
COPY ./microservices/authentication/app.py .
COPY ./creds.json .
# Run the application:
CMD python app.py